import crypto from "crypto";
import { Request } from "express";
import { IncomingHttpHeaders } from "http";
import { CloakingConfig, Config } from "../config";
import { AvailableAccount } from "../accounts/manager";
import { withTimeoutSignal } from "../utils/abort";
import { extractApiKey, hashApiKey } from "../utils/common";

const BASE_URL = "https://api.anthropic.com";
const OAUTH_BETA = "oauth-2025-04-20";
const COMPACT_BETA = "compact-2026-01-12";

/**
 * Dynamic Anthropic-Beta construction — mirrors Claude Code's utils/betas.ts
 * getAllModelBetas(). Real Claude Code sends different betas per model.
 */
function buildBetaHeader(model: string, structured: boolean): string {
  const isHaiku = model.includes("haiku");

  if (isHaiku) {
    if (structured) {
      return "oauth-2025-04-20,interleaved-thinking-2025-05-14,redact-thinking-2026-02-12,context-management-2025-06-27,prompt-caching-scope-2026-01-05,structured-outputs-2025-12-15";
    } else {
      return "oauth-2025-04-20,interleaved-thinking-2025-05-14,redact-thinking-2026-02-12,context-management-2025-06-27,prompt-caching-scope-2026-01-05,claude-code-20250219";
    }
  }

  if (structured) {
    return "claude-code-20250219,oauth-2025-04-20,interleaved-thinking-2025-05-14,redact-thinking-2026-02-12,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advanced-tool-use-2025-11-20,effort-2025-11-24,structured-outputs-2025-12-15";
  }

  return "claude-code-20250219,oauth-2025-04-20,interleaved-thinking-2025-05-14,redact-thinking-2026-02-12,context-management-2025-06-27,prompt-caching-scope-2026-01-05,advanced-tool-use-2025-11-20,effort-2025-11-24";
}

function inferredBetasFromBody(body: any): string[] {
  const edits = body?.context_management?.edits;
  if (
    Array.isArray(edits) &&
    edits.some((edit: any) => edit?.type === "compact_20260112")
  ) {
    return [COMPACT_BETA];
  }
  return [];
}

/**
 * Stainless SDK headers — the @anthropic-ai/sdk package (generated by
 * Stainless) injects these automatically on every request. Claude Code
 * never sets them explicitly; the SDK does.  We replicate them here since
 * we bypass the SDK and use raw fetch().
 *
 * Values should match the SDK version that the target Claude Code release
 * bundles. "0.74.0" corresponds to CLI ≈ 2.1.88.
 */
function getStainlessArch(): string {
  const arch = process.arch;
  if (arch === "arm64") return "arm64";
  if (arch === "x64") return "x64";
  return "x86";
}

function getStainlessOs(): string {
  const platform = process.platform;
  if (platform === "darwin") return "MacOS";
  if (platform === "win32") return "Windows";
  if (platform === "freebsd") return "FreeBSD";
  return "Linux";
}

/**
 * Per-API-key session IDs — mimics Claude Code's bootstrap/state.ts.
 *
 * Real Claude Code: one randomUUID() per CLI process, reused for every API
 * call in that session, regenerated on /clear.
 *
 * auth2api is a long-running server, so a single global session ID would look
 * like one CLI session that never closes. Instead we maintain one session ID
 * per client API key (≈ one "CLI process" per user). Each session ID expires
 * after SESSION_TTL_MS of inactivity so repeated use still looks like a human
 * reopening their terminal periodically.
 */
const SESSION_TTL_MIN = 30 * 60 * 1000; // 30 minutes
const SESSION_TTL_MAX = 300 * 60 * 1000; // 300 minutes
const sessionMap = new Map<
  string,
  { id: string; lastUsed: number; ttl: number }
>();

function randomTTL(): number {
  return SESSION_TTL_MIN + Math.random() * (SESSION_TTL_MAX - SESSION_TTL_MIN);
}

export function getSessionID(apiKeyHash: string): string {
  const now = Date.now();
  const entry = sessionMap.get(apiKeyHash);
  if (entry && now - entry.lastUsed < entry.ttl) {
    entry.lastUsed = now;
    return entry.id;
  }
  // Clean up expired sessions
  for (const [key, val] of sessionMap) {
    if (now - val.lastUsed >= val.ttl) sessionMap.delete(key);
  }
  const id = crypto.randomUUID();
  sessionMap.set(apiKeyHash, { id, lastUsed: now, ttl: randomTTL() });
  return id;
}

/** Default values */
export const DEFAULT_CLI_VERSION = "2.1.88";
export const DEFAULT_ENTRYPOINT = "cli";

function buildHeaders(
  token: string,
  stream: boolean,
  timeoutMs: number,
  model: string,
  cloaking: CloakingConfig,
  apiKeyHash?: string,
  structured?: boolean,
  extraHeaders?: Record<string, string>,
  inferredBetas: string[] = [],
): Record<string, string> {
  const cliVersion = cloaking["cli-version"] || DEFAULT_CLI_VERSION;
  const entrypoint = cloaking.entrypoint || DEFAULT_ENTRYPOINT;
  const sessionID = getSessionID(apiKeyHash || "default");

  // Header casing from mitmproxy capture of real Claude Code CLI:
  // - anthropic-*, x-app, x-client-request-id: lowercase
  // - Everything else: capitalized
  const headers: Record<string, string> = {
    // Capitalized headers
    "Content-Type": "application/json",
    Authorization: `Bearer ${token}`,
    "User-Agent": `claude-cli/${cliVersion} (external, ${entrypoint})`,
    "X-Claude-Code-Session-Id": sessionID,
    "X-Stainless-Lang": "js",
    "X-Stainless-Package-Version": "0.74.0",
    "X-Stainless-Runtime": "node",
    "X-Stainless-Runtime-Version": "v22.13.0",
    "X-Stainless-Arch": getStainlessArch(),
    "X-Stainless-Os": getStainlessOs(),
    "X-Stainless-Timeout": String(Math.max(1, Math.ceil(timeoutMs / 1000))),
    "X-Stainless-Retry-Count": "0",
    Accept: stream ? "text/event-stream" : "application/json",
    // Lowercase headers
    "anthropic-dangerous-direct-browser-access": "true",
    "anthropic-version": "2023-06-01",
    "x-app": "cli",
    "x-client-request-id": crypto.randomUUID(),
  };

  // Override with extra headers (e.g. anthropic-* from claude-cli clients)
  if (extraHeaders) {
    Object.assign(headers, extraHeaders);
  }

  const beta = headers["anthropic-beta"];

  if (typeof beta == "string") {
    const betas = beta
      .split(",")
      .map((b) => b.trim())
      .filter(Boolean);
    if (!betas.includes(OAUTH_BETA)) {
      betas.unshift(OAUTH_BETA);
    }
    betas.push(...inferredBetas);
    headers["anthropic-beta"] = [...new Set(betas)].join(",");
  } else {
    headers["anthropic-beta"] = [
      ...new Set([
        ...buildBetaHeader(model, !!structured).split(","),
        ...inferredBetas,
      ]),
    ].join(",");
  }

  return headers;
}

function extractPassthroughHeaders(
  headers: IncomingHttpHeaders,
): Record<string, string> | undefined {
  const userAgent = headers["user-agent"] || "";
  if (
    typeof userAgent !== "string" ||
    !userAgent.toLowerCase().startsWith("claude-cli")
  ) {
    return undefined;
  }
  const passthrough: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers)) {
    if (key.startsWith("anthropic") && typeof value === "string") {
      passthrough[key] = value;
    }
  }
  const sessionID = headers["x-claude-code-session-id"];
  if (typeof sessionID === "string") {
    passthrough["X-Claude-Code-Session-Id"] = sessionID;
  }
  return passthrough;
}

export interface CallMessagesOptions {
  body?: any;
  request: Request;
  account: AvailableAccount;
  config: Config;
  structured?: boolean;
  signal?: AbortSignal;
}

export async function callAnthropicMessages(
  options: CallMessagesOptions,
): Promise<Response> {
  const { request, account, config, structured } = options;
  const body = options.body ?? request.body;
  const url = `${BASE_URL}/v1/messages?beta=true`;
  const stream = !!body.stream;
  const model = body.model || "claude-sonnet-4-6";
  const apiKeyHash = hashApiKey(extractApiKey(request.headers));
  const timeoutMs = stream
    ? config.timeouts["stream-messages-ms"]
    : config.timeouts["messages-ms"];
  const newHeaders = buildHeaders(
    account.token.accessToken,
    stream,
    timeoutMs,
    model,
    config.cloaking,
    apiKeyHash,
    structured,
    extractPassthroughHeaders(request.headers),
    inferredBetasFromBody(body),
  );

  const response = await fetch(url, {
    method: "POST",
    headers: newHeaders,
    body: JSON.stringify(body),
    signal: withTimeoutSignal(timeoutMs, options.signal),
  });

  return response;
}

export interface CallCountTokensOptions {
  request: Request;
  account: AvailableAccount;
  config: Config;
  signal?: AbortSignal;
}

export async function callAnthropicCountTokens(
  options: CallCountTokensOptions,
): Promise<Response> {
  const { request, account, config } = options;
  const body = request.body ?? {};
  const url = `${BASE_URL}/v1/messages/count_tokens?beta=true`;
  const model = body?.model || "claude-sonnet-4-6";
  const apiKeyHash = hashApiKey(extractApiKey(request.headers));
  const timeoutMs = config.timeouts["count-tokens-ms"];
  const newHeaders = buildHeaders(
    account.token.accessToken,
    false,
    timeoutMs,
    model,
    config.cloaking,
    apiKeyHash,
    undefined,
    extractPassthroughHeaders(request.headers),
    inferredBetasFromBody(body),
  );

  const response = await fetch(url, {
    method: "POST",
    headers: newHeaders,
    body: JSON.stringify(body),
    signal: withTimeoutSignal(timeoutMs, options.signal),
  });

  return response;
}
